export enum CarColor {
    Red = 'red',
    Green = 'green',
    Blue = 'blue',
    Yellow = 'yellow',
    Black = 'black',
    White = 'white',
    Gray = 'gray',
    Silver = 'silver',
    Orange = 'orange',
    Brown = 'brown',
    Purple = 'purple',
    Pink = 'pink',
    Gold = 'gold',
}